version: '3'
services:
  mysql:
   container_name: mysql
   image: mysql/mysql-server:5.7
   environment:
    MYSQL_DATABASE: estacionamento
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
   ports:
   - "3306:3306"
   networks:
      - main

  backend:
    container_name: backend
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    depends_on:
      - mysql
    networks:
      - main

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - mysql
      - backend
    networks:
      - main

networks:
  main: